const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    // ADmin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',
     // STATUS
    FETCH_STATUS_START: 'FETCH_STATUS_START',
    FETCH_STATUS_SUCCESS: 'FETCH_STATUS_SUCCESS',
    FETCH_STATUS_FAILED: 'FETCH_STATUS_FAILED',

    // ROLE
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAIL',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAIL',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAIL',

    FETCH_ALL_USER_SUCCESS: 'FETCH_ALL_USER_SUCCESS',
    FETCH_ALL_USER_FAILED: 'FETCH_ALL_USER_FAILED',

    FETCH_TOP_DT_SUCCESS: 'FETCH_TOP_DT_SUCCESS',
    FETCH_TOP_DT_FAILED: 'FETCH_TOP_DT_FAILED',

    FETCH_ALL_SP_SUCCESS: 'FETCH_ALL_SP_SUCCESS',
    FETCH_ALL_SP_FAILED: 'FETCH_ALL_SP_FAILED',

    FETCH_SAVE_INFO_SP_SUCCESS: 'FETCH_SAVE_INFO_SP_SUCCESS',
    FETCH_FAIL_INFO_SP_FAILED: 'FETCH_FAIL_INFO_SP_FAILED',

    //sản phẩm
    FETCH_ALL_SANPHAM_SUCCESS: 'FETCH_ALL_SANPHAM_SUCCESS',
    FETCH_ALL_SANPHAM_FAILED: 'FETCH_ALL_SANPHAM_FAILED',

    CREATE_SANPHAM_SUCCESS: 'CREATE_SANPHAM_SUCCESS',
    CREATE_SANPHAM_FAILED: 'CREATE_SANPHAM_FAIL',

    FETCH_SAVE_INFO_SANPHAM_SUCCESS: 'FETCH_SAVE_INFO_SANPHAM_SUCCESS',
    FETCH_FAIL_INFO_SANPHAM_FAILED: 'FETCH_FAIL_INFO_SANPHAM_FAILED',

    EDIT_SANPHAM_SUCCESS: 'EDIT_SANPHAM_SUCCESS',
    EDIT_SANPHAM_FAILED: 'EDIT_SANPHAM_FAIL',

    DELETE_SANPHAM_SUCCESS: 'DELETE_SANPHAM_SUCCESS',
    DELETE_SANPHAM_FAILED: 'DELETE_SANPHAM_FAIL',

    //loại sản phẩm
    FETCH_ALL_LOAISANPHAM_START: 'FETCH_ALL_LOAISANPHAM_START',
    FETCH_ALL_LOAISANPHAM_SUCCESS:'FETCH_ALL_LOAISANPHAM_SUCCESS',
    FETCH_ALL_LOAISANPHAM_FAILED: 'FETCH_ALL_LOAISANPHAM_FAILED',

    CREATE_LOAISANPHAM_SUCCESS: 'CREATE_LOAISANPHAM_SUCCESS',
    CREATE_LOAISANPHAM_FAILED: 'CREATE_LOAISANPHAM_FAIL',

    EDIT_LOAISANPHAM_SUCCESS: 'EDIT_LOAISANPHAM_SUCCESS',
    EDIT_LOAISANPHAM_FAILED: 'EDIT_LOAISANPHAM_FAIL',

    DELETE_LOAISANPHAM_SUCCESS: 'DELETE_LOAISANPHAM_SUCCESS',
    DELETE_LOAISANPHAM_FAILED: 'DELETE_LOAISANPHAM_FAIL',

    //danh mục
    FETCH_ALL_LOAISANPHAM_START: 'FETCH_ALL_LOAISANPHAM_START',
    CREATE_DANHMUC_SUCCESS: 'CREATE_DANHMUC_SUCCESS',
    CREATE_LOAISANPHAM_FAILED: 'CREATE_LOAISANPHAM_FAIL',
    FETCH_ALL_DANHMUC_SUCCESS: 'FETCH_ALL_DANHMUC_SUCCESS',
    FETCH_ALL_DANHMUC_FAILED: 'FETCH_ALL_DANHMUC_FAILED',

    EDIT_DANHMUC_SUCCESS: 'EDIT_DANHMUC_SUCCESS',
    EDIT_DANHMUC_FAIL: 'EDIT_DANHMUC_FAIL',

    // tìm
    SEARCH_LOAISP_SUCCESS: 'SEARCH_LOAISP_SUCCESS',
    SEARCH_LOAISP_FAILED: 'SEARCH_LOAISP_FAILED'

    
})

export default actionTypes;